name: s3rebro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55282
title: S3rebro
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c2d2f'
    - '#5e696b'
    - '#d2bc2a'
    - '#929999'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
