name: s3rebro
favicon: null
layout_spectrum: 0.88635
typography_spectrum: 0.38072
title: S3rebro
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c2d2f'
    - '#5e696b'
    - '#a5c4c6'
    - '#d2bc2a'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
